- hosts: all
  tasks:
    - name: Setting the Docker Yum Repo
      yum_repository:
         name: "docker_yum"
         description: "Configure Docker"
         baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
         gpgcheck: no

    - name: "docker Installation"
      command: "yum install docker-ce --nobest -y"

    - name: "create a directory to store the data"
      file: 
          state: directory
          path: "/root/WS"

    - name: "Copying the Data"
      copy:
          dest: "/root/WS/index.html"
          content: "Hello! Working Great"

    - name: "Starting the Docker Services"
      service:
           name: docker
           state: started
           enabled: yes

    - pip:
           name: docker-py

    - name: "Puuling the HTTPD image from the docker hub"
      docker_container: 
           name: "httpd_container"
           image: httpd
           pull: yes
           ports:
             - "8080:80"
           volumes:
             - /root/WS/:/usr/local/apache2/htdocs/
           detach: yes
           state: started
          
           
